# Running rmats-turbo in the cloud 

## ERROR in running the post step on the 1113 samples 

**From Eric**: 
There was a useful error message in the job.err.log for the failed task that I missed before:
2021-10-20T11:29:51.670227232Z /sbgenomics/Projects/60da54a2-bba2-4075-9fee-8cb904f7497b/aligned-reads/4e4d7817-d086-43f9-9f42-f78cf5b17941.Aligned.out.sorted.bam given 2 times in input

From looking at the aggregated.csv output file and the log from the aggregate_csv_files step of the failed task it looks like the two input files with that bam are _484_b1.txt, _1235_b1.txt:
https://cavatica.sbgenomics.com/u/jiadams/cog-analysis/files/616f58abbaf08f5601b0310e/
https://cavatica.sbgenomics.com/u/jiadams/cog-analysis/files/616f58acbaf08f5601b04973/


It looks like 484 is from an older prep task: https://cavatica.sbgenomics.com/u/jiadams/rmats-app-dev-ja/tasks/84048262-6d66-48c7-b21e-a450708d8b72/
and 1235 is from a newer prep task with "new gtf": https://cavatica.sbgenomics.com/u/jiadams/rmats-app-dev-ja/tasks/9689d4e0-4118-43e7-ae35-f98d9e125a53/


It looks like 758d3606-f5e8-47b0-afad-de888952784e.Aligned.out.sorted.bam is the missing bam of the 1113 and this b1.txt that didn't have its name changed might be the missing file:
https://cavatica.sbgenomics.com/u/jiadams/cog-analysis/files/616f58a8baf08f5601b010a7/


**ACTION**

I re-ran the post step after removing the ```_484_b1.txt``` fild and instead including ```b1.txt```. 
